### ISSUE TITLE
Implement LNotification style

### ISSUE THREAD

**Issue by berthojoris** [ParsePlatform/PushTutorial#17]
What if parse.com team tries to make the implementation of the SDK into LNotifikasi Parse for a new style?

**Comment by bnham** [comment]
The Parse SDK will automatically create a simple notification using the "title" and "alert" keys from the push payload. If you want to do something more sophisticated, we recommend that you override onPushReceive() in [ParsePushBroadcastReceiver](https://parse.com/docs/android/api/com/parse/ParsePushBroadcastReceiver.html) and create whatever notification you want via Android's NotificationManager API. (The default implementation of onPushReceive() creates the simple notification I described. The notification is created with options so that when it is opened, it sends the com.parse.push.intent.OPEN intent when opened, or the com.parse.push.intent.DELETE intent when deleted.)
