### ISSUE TITLE
REST API error, I couldn't not receive any push by android device.

### ISSUE THREAD

**Issue by scolin912** [ParsePlatform/PushTutorial#18]
I'm trying to use REST API to send a push notification to my android device

On the first, I receive Missing the push data, please see below.

C:\>curl -X POST -H "X-Parse-Application-Id: Y5D6DVdimngH59TYabxYnsky1XKa0kfObQf
ZWL4T" -H "X-Parse-REST-API-Key: Gz5nESwcRrCWeTjAx3GWMYEcm7RRu5bavlDFaBOu" -H "C
ontent-Type: application/json" -d "{}" -k https://api.parse.com/1/push
{"code":115,"error":"Missing the push data."}

On the next, maybe I forgot to include channels and diviceType, so I modify the console and receive below.

C:\>curl -X POST -H "X-Parse-Application-Id: Y5D6DVdimngH59TYabxYnsky1XKa0kfObQf
ZWL4T" -H "X-Parse-REST-API-Key: Gz5nESwcRrCWeTjAx3GWMYEcm7RRu5bavlDFaBOu"-H "Co
ntent-Type: application/json"-d '{"channels": "", "deviceType": "android" }'http
s://api.parse.com/1/push
curl: (6) Could not resolve host: Content-Type
curl: (3) [globbing] unmatched brace in column 2
curl: (6) Could not resolve host: ,
curl: (6) Could not resolve host: deviceType
curl: (6) Could not resolve host: android
curl: (3) [globbing] unmatched close brace/bracket in column 1

How do I receive notification by android device?

**Comment by bnham** [comment]
The best way to get in touch with our support is by clicking "Report a Bug" at https://parse.com/help. This will bring you to a handy pre-filled form with bug info and log the bug into our tracking system. Please direct further support requests to that channel.

For your first curl request, you are not supplying a number of required fields for the /1/push endpoint. An empty JSON object is not a valid input to that endpoint. For instance, under "sending pushes to queries" described at https://parse.com/docs/push_guide#sending-queries/REST, here is a possible valid push payload that contains a constraint (in the "where" property) and some push data (in the "data" property):

      {
        "where": {
          "injuryReports": true
        },
        "data": {
          "alert": "Willie Hayes injured by own pop fly."
        }
      }

In your second curl, you have some mis-matched quotes which cause curl to interpret Content as the host for the request instead of api.parse.com.

Finally, you should generally not expose your API keys (especially your REST and master keys) on a public forum. See http://blog.parse.com/learn/engineering/parse-security-i-are-you-the-key-master/ for more info.
