### ISSUE TITLE
Android Parse Push

### ISSUE THREAD

**Issue by sayoojvalsan** [ParsePlatform/PushTutorial#25]
I was looking at the tutorial and looks like the MainActivity doesnt do any push. All I see is there are methods to refresh and save user data. Am I missing something ?

**Comment by hallucinogen** [comment]
Yes, this tutorial is not sending any push. The Android tutorial (and all of the tutorials in this repo) is a tutorial for receiving push notification.

We did not give an example for sending push from client in this tutorial because sending push directly from client is discouraged. Read more about this here: http://blog.parse.com/learn/engineering/the-dangerous-world-of-client-push/

Hope it helps!
